//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.GDI;

[assembly: RegisterDocumentType(AccordionTab.CLASS_NAME, typeof(AccordionTab))]

namespace CMS.DocumentEngine.Types.GDI
{
	/// <summary>
	/// Represents a content item of type AccordionTab.
	/// </summary>
	public partial class AccordionTab : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "GDI.AccordionTab";


		/// <summary>
		/// The instance of the class that provides extended API for working with AccordionTab fields.
		/// </summary>
		private readonly AccordionTabFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// AccordionTabID.
		/// </summary>
		[DatabaseIDField]
		public int AccordionTabID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("AccordionTabID"), 0);
			}
			set
			{
				SetValue("AccordionTabID", value);
			}
		}


		/// <summary>
		/// Accordion Name.
		/// </summary>
		[DatabaseField]
		public string AccordionName
		{
			get
			{
				return ValidationHelper.GetString(GetValue("AccordionName"), @"");
			}
			set
			{
				SetValue("AccordionName", value);
			}
		}


		/// <summary>
		/// Accordion Title.
		/// </summary>
		[DatabaseField]
		public string AccordionTitle
		{
			get
			{
				return ValidationHelper.GetString(GetValue("AccordionTitle"), @"");
			}
			set
			{
				SetValue("AccordionTitle", value);
			}
		}


		/// <summary>
		/// Left Section.
		/// </summary>
		[DatabaseField]
		public string LeftSection
		{
			get
			{
				return ValidationHelper.GetString(GetValue("LeftSection"), @"");
			}
			set
			{
				SetValue("LeftSection", value);
			}
		}


		/// <summary>
		/// Right Section.
		/// </summary>
		[DatabaseField]
		public string RightSection
		{
			get
			{
				return ValidationHelper.GetString(GetValue("RightSection"), @"");
			}
			set
			{
				SetValue("RightSection", value);
			}
		}


		/// <summary>
		/// Button Text.
		/// </summary>
		[DatabaseField]
		public string ButtonText
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ButtonText"), @"");
			}
			set
			{
				SetValue("ButtonText", value);
			}
		}


		/// <summary>
		/// Button URL.
		/// </summary>
		[DatabaseField]
		public string ButtonURL
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ButtonURL"), @"");
			}
			set
			{
				SetValue("ButtonURL", value);
			}
		}


		/// <summary>
		/// Tab Image.
		/// </summary>
		[DatabaseField]
		public string TabImage
		{
			get
			{
				return ValidationHelper.GetString(GetValue("TabImage"), @"/GDI/media/GDI/tab-corner.jpg");
			}
			set
			{
				SetValue("TabImage", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with AccordionTab fields.
		/// </summary>
		[RegisterProperty]
		public AccordionTabFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with AccordionTab fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class AccordionTabFields : AbstractHierarchicalObject<AccordionTabFields>
		{
			/// <summary>
			/// The content item of type AccordionTab that is a target of the extended API.
			/// </summary>
			private readonly AccordionTab mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="AccordionTabFields" /> class with the specified content item of type AccordionTab.
			/// </summary>
			/// <param name="instance">The content item of type AccordionTab that is a target of the extended API.</param>
			public AccordionTabFields(AccordionTab instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// AccordionTabID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.AccordionTabID;
				}
				set
				{
					mInstance.AccordionTabID = value;
				}
			}


			/// <summary>
			/// Accordion Name.
			/// </summary>
			public string AccordionName
			{
				get
				{
					return mInstance.AccordionName;
				}
				set
				{
					mInstance.AccordionName = value;
				}
			}


			/// <summary>
			/// Accordion Title.
			/// </summary>
			public string AccordionTitle
			{
				get
				{
					return mInstance.AccordionTitle;
				}
				set
				{
					mInstance.AccordionTitle = value;
				}
			}


			/// <summary>
			/// Left Section.
			/// </summary>
			public string LeftSection
			{
				get
				{
					return mInstance.LeftSection;
				}
				set
				{
					mInstance.LeftSection = value;
				}
			}


			/// <summary>
			/// Right Section.
			/// </summary>
			public string RightSection
			{
				get
				{
					return mInstance.RightSection;
				}
				set
				{
					mInstance.RightSection = value;
				}
			}


			/// <summary>
			/// Button Text.
			/// </summary>
			public string ButtonText
			{
				get
				{
					return mInstance.ButtonText;
				}
				set
				{
					mInstance.ButtonText = value;
				}
			}


			/// <summary>
			/// Button URL.
			/// </summary>
			public string ButtonURL
			{
				get
				{
					return mInstance.ButtonURL;
				}
				set
				{
					mInstance.ButtonURL = value;
				}
			}


			/// <summary>
			/// Tab Image.
			/// </summary>
			public string TabImage
			{
				get
				{
					return mInstance.TabImage;
				}
				set
				{
					mInstance.TabImage = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="AccordionTab" /> class.
		/// </summary>
		public AccordionTab() : base(CLASS_NAME)
		{
			mFields = new AccordionTabFields(this);
		}

		#endregion
	}
}