//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.GDI;

[assembly: RegisterDocumentType(Accordion.CLASS_NAME, typeof(Accordion))]

namespace CMS.DocumentEngine.Types.GDI
{
	/// <summary>
	/// Represents a content item of type Accordion.
	/// </summary>
	public partial class Accordion : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "GDI.Accordion";


		/// <summary>
		/// The instance of the class that provides extended API for working with Accordion fields.
		/// </summary>
		private readonly AccordionFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// AccordionID.
		/// </summary>
		[DatabaseIDField]
		public int AccordionID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("AccordionID"), 0);
			}
			set
			{
				SetValue("AccordionID", value);
			}
		}


		/// <summary>
		/// Accordion Name.
		/// </summary>
		[DatabaseField]
		public string AccordionName
		{
			get
			{
				return ValidationHelper.GetString(GetValue("AccordionName"), @"");
			}
			set
			{
				SetValue("AccordionName", value);
			}
		}


		/// <summary>
		/// Accordion Title.
		/// </summary>
		[DatabaseField]
		public string AccordionTitle
		{
			get
			{
				return ValidationHelper.GetString(GetValue("AccordionTitle"), @"");
			}
			set
			{
				SetValue("AccordionTitle", value);
			}
		}


		/// <summary>
		/// Left Section.
		/// </summary>
		[DatabaseField]
		public string LeftSection
		{
			get
			{
				return ValidationHelper.GetString(GetValue("LeftSection"), @"");
			}
			set
			{
				SetValue("LeftSection", value);
			}
		}


		/// <summary>
		/// Right Section.
		/// </summary>
		[DatabaseField]
		public string RightSection
		{
			get
			{
				return ValidationHelper.GetString(GetValue("RightSection"), @"");
			}
			set
			{
				SetValue("RightSection", value);
			}
		}


		/// <summary>
		/// Button Text.
		/// </summary>
		[DatabaseField]
		public string ButtonText
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ButtonText"), @"");
			}
			set
			{
				SetValue("ButtonText", value);
			}
		}


		/// <summary>
		/// Button URL.
		/// </summary>
		[DatabaseField]
		public string ButtonURL
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ButtonURL"), @"");
			}
			set
			{
				SetValue("ButtonURL", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with Accordion fields.
		/// </summary>
		[RegisterProperty]
		public AccordionFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with Accordion fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class AccordionFields : AbstractHierarchicalObject<AccordionFields>
		{
			/// <summary>
			/// The content item of type Accordion that is a target of the extended API.
			/// </summary>
			private readonly Accordion mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="AccordionFields" /> class with the specified content item of type Accordion.
			/// </summary>
			/// <param name="instance">The content item of type Accordion that is a target of the extended API.</param>
			public AccordionFields(Accordion instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// AccordionID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.AccordionID;
				}
				set
				{
					mInstance.AccordionID = value;
				}
			}


			/// <summary>
			/// Accordion Name.
			/// </summary>
			public string Name
			{
				get
				{
					return mInstance.AccordionName;
				}
				set
				{
					mInstance.AccordionName = value;
				}
			}


			/// <summary>
			/// Accordion Title.
			/// </summary>
			public string Title
			{
				get
				{
					return mInstance.AccordionTitle;
				}
				set
				{
					mInstance.AccordionTitle = value;
				}
			}


			/// <summary>
			/// Left Section.
			/// </summary>
			public string LeftSection
			{
				get
				{
					return mInstance.LeftSection;
				}
				set
				{
					mInstance.LeftSection = value;
				}
			}


			/// <summary>
			/// Right Section.
			/// </summary>
			public string RightSection
			{
				get
				{
					return mInstance.RightSection;
				}
				set
				{
					mInstance.RightSection = value;
				}
			}


			/// <summary>
			/// Button Text.
			/// </summary>
			public string ButtonText
			{
				get
				{
					return mInstance.ButtonText;
				}
				set
				{
					mInstance.ButtonText = value;
				}
			}


			/// <summary>
			/// Button URL.
			/// </summary>
			public string ButtonURL
			{
				get
				{
					return mInstance.ButtonURL;
				}
				set
				{
					mInstance.ButtonURL = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="Accordion" /> class.
		/// </summary>
		public Accordion() : base(CLASS_NAME)
		{
			mFields = new AccordionFields(this);
		}

		#endregion
	}
}