//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.GDI;

[assembly: RegisterDocumentType(EmailBusiness.CLASS_NAME, typeof(EmailBusiness))]

namespace CMS.DocumentEngine.Types.GDI
{
	/// <summary>
	/// Represents a content item of type EmailBusiness.
	/// </summary>
	public partial class EmailBusiness : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "GDI.EmailBusiness";


		/// <summary>
		/// The instance of the class that provides extended API for working with EmailBusiness fields.
		/// </summary>
		private readonly EmailBusinessFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// EmailSignUpID.
		/// </summary>
		[DatabaseIDField]
		public int EmailSignUpID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("EmailSignUpID"), 0);
			}
			set
			{
				SetValue("EmailSignUpID", value);
			}
		}


		/// <summary>
		/// Business Title.
		/// </summary>
		[DatabaseField]
		public string Title
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Title"), @"");
			}
			set
			{
				SetValue("Title", value);
			}
		}


		/// <summary>
		/// Business Description.
		/// </summary>
		[DatabaseField]
		public string Description
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Description"), @"");
			}
			set
			{
				SetValue("Description", value);
			}
		}


		/// <summary>
		/// Background Color.
		/// </summary>
		[DatabaseField]
		public string BackgroundColor
		{
			get
			{
				return ValidationHelper.GetString(GetValue("BackgroundColor"), @"");
			}
			set
			{
				SetValue("BackgroundColor", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with EmailBusiness fields.
		/// </summary>
		[RegisterProperty]
		public EmailBusinessFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with EmailBusiness fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class EmailBusinessFields : AbstractHierarchicalObject<EmailBusinessFields>
		{
			/// <summary>
			/// The content item of type EmailBusiness that is a target of the extended API.
			/// </summary>
			private readonly EmailBusiness mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="EmailBusinessFields" /> class with the specified content item of type EmailBusiness.
			/// </summary>
			/// <param name="instance">The content item of type EmailBusiness that is a target of the extended API.</param>
			public EmailBusinessFields(EmailBusiness instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// EmailSignUpID.
			/// </summary>
			public int EmailSignUpID
			{
				get
				{
					return mInstance.EmailSignUpID;
				}
				set
				{
					mInstance.EmailSignUpID = value;
				}
			}


			/// <summary>
			/// Business Title.
			/// </summary>
			public string Title
			{
				get
				{
					return mInstance.Title;
				}
				set
				{
					mInstance.Title = value;
				}
			}


			/// <summary>
			/// Business Description.
			/// </summary>
			public string Description
			{
				get
				{
					return mInstance.Description;
				}
				set
				{
					mInstance.Description = value;
				}
			}


			/// <summary>
			/// Background Color.
			/// </summary>
			public string BackgroundColor
			{
				get
				{
					return mInstance.BackgroundColor;
				}
				set
				{
					mInstance.BackgroundColor = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="EmailBusiness" /> class.
		/// </summary>
		public EmailBusiness() : base(CLASS_NAME)
		{
			mFields = new EmailBusinessFields(this);
		}

		#endregion
	}
}