//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.GDI;

[assembly: RegisterDocumentType(ExternalPageLinks.CLASS_NAME, typeof(ExternalPageLinks))]

namespace CMS.DocumentEngine.Types.GDI
{
	/// <summary>
	/// Represents a content item of type ExternalPageLinks.
	/// </summary>
	public partial class ExternalPageLinks : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "GDI.ExternalPageLinks";


		/// <summary>
		/// The instance of the class that provides extended API for working with ExternalPageLinks fields.
		/// </summary>
		private readonly ExternalPageLinksFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// ExternalPageLinksID.
		/// </summary>
		[DatabaseIDField]
		public int ExternalPageLinksID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("ExternalPageLinksID"), 0);
			}
			set
			{
				SetValue("ExternalPageLinksID", value);
			}
		}


		/// <summary>
		/// Page Title.
		/// </summary>
		[DatabaseField]
		public string PageTitle
		{
			get
			{
				return ValidationHelper.GetString(GetValue("PageTitle"), @"");
			}
			set
			{
				SetValue("PageTitle", value);
			}
		}


		/// <summary>
		/// PageUrl.
		/// </summary>
		[DatabaseField]
		public string PageUrl
		{
			get
			{
				return ValidationHelper.GetString(GetValue("PageUrl"), @"");
			}
			set
			{
				SetValue("PageUrl", value);
			}
		}


		/// <summary>
		/// Page Url Target.
		/// </summary>
		[DatabaseField]
		public string PageUrlTarget
		{
			get
			{
				return ValidationHelper.GetString(GetValue("PageUrlTarget"), @"");
			}
			set
			{
				SetValue("PageUrlTarget", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with ExternalPageLinks fields.
		/// </summary>
		[RegisterProperty]
		public ExternalPageLinksFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with ExternalPageLinks fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class ExternalPageLinksFields : AbstractHierarchicalObject<ExternalPageLinksFields>
		{
			/// <summary>
			/// The content item of type ExternalPageLinks that is a target of the extended API.
			/// </summary>
			private readonly ExternalPageLinks mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="ExternalPageLinksFields" /> class with the specified content item of type ExternalPageLinks.
			/// </summary>
			/// <param name="instance">The content item of type ExternalPageLinks that is a target of the extended API.</param>
			public ExternalPageLinksFields(ExternalPageLinks instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// ExternalPageLinksID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.ExternalPageLinksID;
				}
				set
				{
					mInstance.ExternalPageLinksID = value;
				}
			}


			/// <summary>
			/// Page Title.
			/// </summary>
			public string PageTitle
			{
				get
				{
					return mInstance.PageTitle;
				}
				set
				{
					mInstance.PageTitle = value;
				}
			}


			/// <summary>
			/// PageUrl.
			/// </summary>
			public string PageUrl
			{
				get
				{
					return mInstance.PageUrl;
				}
				set
				{
					mInstance.PageUrl = value;
				}
			}


			/// <summary>
			/// Page Url Target.
			/// </summary>
			public string PageUrlTarget
			{
				get
				{
					return mInstance.PageUrlTarget;
				}
				set
				{
					mInstance.PageUrlTarget = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="ExternalPageLinks" /> class.
		/// </summary>
		public ExternalPageLinks() : base(CLASS_NAME)
		{
			mFields = new ExternalPageLinksFields(this);
		}

		#endregion
	}
}