//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.GDI;

[assembly: RegisterDocumentType(PageConfiguration.CLASS_NAME, typeof(PageConfiguration))]

namespace CMS.DocumentEngine.Types.GDI
{
	/// <summary>
	/// Represents a content item of type PageConfiguration.
	/// </summary>
	public partial class PageConfiguration : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "GDI.PageConfiguration";


		/// <summary>
		/// The instance of the class that provides extended API for working with PageConfiguration fields.
		/// </summary>
		private readonly PageConfigurationFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// PageConfigurationID.
		/// </summary>
		[DatabaseIDField]
		public int PageConfigurationID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("PageConfigurationID"), 0);
			}
			set
			{
				SetValue("PageConfigurationID", value);
			}
		}


		/// <summary>
		/// Header Logo.
		/// </summary>
		[DatabaseField]
		public string HeaderLogo
		{
			get
			{
				return ValidationHelper.GetString(GetValue("HeaderLogo"), @"");
			}
			set
			{
				SetValue("HeaderLogo", value);
			}
		}


		/// <summary>
		/// Header Logo Alt Text.
		/// </summary>
		[DatabaseField]
		public string HeaderLogoAltText
		{
			get
			{
				return ValidationHelper.GetString(GetValue("HeaderLogoAltText"), @"");
			}
			set
			{
				SetValue("HeaderLogoAltText", value);
			}
		}


		/// <summary>
		/// Header Logo Link.
		/// </summary>
		[DatabaseField]
		public string HeaderLogoLink
		{
			get
			{
				return ValidationHelper.GetString(GetValue("HeaderLogoLink"), @"");
			}
			set
			{
				SetValue("HeaderLogoLink", value);
			}
		}


		/// <summary>
		/// Footer Logo  Link.
		/// </summary>
		[DatabaseField]
		public string FooterLogoLink
		{
			get
			{
				return ValidationHelper.GetString(GetValue("FooterLogoLink"), @"");
			}
			set
			{
				SetValue("FooterLogoLink", value);
			}
		}


		/// <summary>
		/// Footer Logo Class.
		/// </summary>
		[DatabaseField]
		public string FooterLogoClass
		{
			get
			{
				return ValidationHelper.GetString(GetValue("FooterLogoClass"), @"");
			}
			set
			{
				SetValue("FooterLogoClass", value);
			}
		}


		/// <summary>
		/// Copy Right Text.
		/// </summary>
		[DatabaseField]
		public string CopyRightText
		{
			get
			{
				return ValidationHelper.GetString(GetValue("CopyRightText"), @"");
			}
			set
			{
				SetValue("CopyRightText", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with PageConfiguration fields.
		/// </summary>
		[RegisterProperty]
		public PageConfigurationFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with PageConfiguration fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class PageConfigurationFields : AbstractHierarchicalObject<PageConfigurationFields>
		{
			/// <summary>
			/// The content item of type PageConfiguration that is a target of the extended API.
			/// </summary>
			private readonly PageConfiguration mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="PageConfigurationFields" /> class with the specified content item of type PageConfiguration.
			/// </summary>
			/// <param name="instance">The content item of type PageConfiguration that is a target of the extended API.</param>
			public PageConfigurationFields(PageConfiguration instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// PageConfigurationID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.PageConfigurationID;
				}
				set
				{
					mInstance.PageConfigurationID = value;
				}
			}


			/// <summary>
			/// Header Logo.
			/// </summary>
			public string HeaderLogo
			{
				get
				{
					return mInstance.HeaderLogo;
				}
				set
				{
					mInstance.HeaderLogo = value;
				}
			}


			/// <summary>
			/// Header Logo Alt Text.
			/// </summary>
			public string HeaderLogoAltText
			{
				get
				{
					return mInstance.HeaderLogoAltText;
				}
				set
				{
					mInstance.HeaderLogoAltText = value;
				}
			}


			/// <summary>
			/// Header Logo Link.
			/// </summary>
			public string HeaderLogoLink
			{
				get
				{
					return mInstance.HeaderLogoLink;
				}
				set
				{
					mInstance.HeaderLogoLink = value;
				}
			}


			/// <summary>
			/// Footer Logo  Link.
			/// </summary>
			public string FooterLogoLink
			{
				get
				{
					return mInstance.FooterLogoLink;
				}
				set
				{
					mInstance.FooterLogoLink = value;
				}
			}


			/// <summary>
			/// Footer Logo Class.
			/// </summary>
			public string FooterLogoClass
			{
				get
				{
					return mInstance.FooterLogoClass;
				}
				set
				{
					mInstance.FooterLogoClass = value;
				}
			}


			/// <summary>
			/// Copy Right Text.
			/// </summary>
			public string CopyRightText
			{
				get
				{
					return mInstance.CopyRightText;
				}
				set
				{
					mInstance.CopyRightText = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="PageConfiguration" /> class.
		/// </summary>
		public PageConfiguration() : base(CLASS_NAME)
		{
			mFields = new PageConfigurationFields(this);
		}

		#endregion
	}
}