//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.GDI;

[assembly: RegisterDocumentType(Robots.CLASS_NAME, typeof(Robots))]

namespace CMS.DocumentEngine.Types.GDI
{
	/// <summary>
	/// Represents a content item of type Robots.
	/// </summary>
	public partial class Robots : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "GDI.Robots";


		/// <summary>
		/// The instance of the class that provides extended API for working with Robots fields.
		/// </summary>
		private readonly RobotsFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// RobotsID.
		/// </summary>
		[DatabaseIDField]
		public int RobotsID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("RobotsID"), 0);
			}
			set
			{
				SetValue("RobotsID", value);
			}
		}


		/// <summary>
		/// Robots Text.
		/// </summary>
		[DatabaseField]
		public string RobotsText
		{
			get
			{
				return ValidationHelper.GetString(GetValue("RobotsText"), @"");
			}
			set
			{
				SetValue("RobotsText", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with Robots fields.
		/// </summary>
		[RegisterProperty]
		public RobotsFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with Robots fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class RobotsFields : AbstractHierarchicalObject<RobotsFields>
		{
			/// <summary>
			/// The content item of type Robots that is a target of the extended API.
			/// </summary>
			private readonly Robots mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="RobotsFields" /> class with the specified content item of type Robots.
			/// </summary>
			/// <param name="instance">The content item of type Robots that is a target of the extended API.</param>
			public RobotsFields(Robots instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// RobotsID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.RobotsID;
				}
				set
				{
					mInstance.RobotsID = value;
				}
			}


			/// <summary>
			/// Robots Text.
			/// </summary>
			public string Text
			{
				get
				{
					return mInstance.RobotsText;
				}
				set
				{
					mInstance.RobotsText = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="Robots" /> class.
		/// </summary>
		public Robots() : base(CLASS_NAME)
		{
			mFields = new RobotsFields(this);
		}

		#endregion
	}
}