//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.GDI;

[assembly: RegisterDocumentType(SocialMedia.CLASS_NAME, typeof(SocialMedia))]

namespace CMS.DocumentEngine.Types.GDI
{
	/// <summary>
	/// Represents a content item of type SocialMedia.
	/// </summary>
	public partial class SocialMedia : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "GDI.SocialMedia";


		/// <summary>
		/// The instance of the class that provides extended API for working with SocialMedia fields.
		/// </summary>
		private readonly SocialMediaFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// SocialMediaID.
		/// </summary>
		[DatabaseIDField]
		public int SocialMediaID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("SocialMediaID"), 0);
			}
			set
			{
				SetValue("SocialMediaID", value);
			}
		}


		/// <summary>
		/// Title.
		/// </summary>
		[DatabaseField]
		public string Title
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Title"), @"");
			}
			set
			{
				SetValue("Title", value);
			}
		}


		/// <summary>
		/// Target.
		/// </summary>
		[DatabaseField]
		public string Target
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Target"), @"");
			}
			set
			{
				SetValue("Target", value);
			}
		}


		/// <summary>
		/// Redirect URL.
		/// </summary>
		[DatabaseField]
		public string RedirectUrl
		{
			get
			{
				return ValidationHelper.GetString(GetValue("RedirectUrl"), @"");
			}
			set
			{
				SetValue("RedirectUrl", value);
			}
		}


		/// <summary>
		/// Icon Class.
		/// </summary>
		[DatabaseField]
		public string IconClass
		{
			get
			{
				return ValidationHelper.GetString(GetValue("IconClass"), @"");
			}
			set
			{
				SetValue("IconClass", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with SocialMedia fields.
		/// </summary>
		[RegisterProperty]
		public SocialMediaFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with SocialMedia fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class SocialMediaFields : AbstractHierarchicalObject<SocialMediaFields>
		{
			/// <summary>
			/// The content item of type SocialMedia that is a target of the extended API.
			/// </summary>
			private readonly SocialMedia mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="SocialMediaFields" /> class with the specified content item of type SocialMedia.
			/// </summary>
			/// <param name="instance">The content item of type SocialMedia that is a target of the extended API.</param>
			public SocialMediaFields(SocialMedia instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// SocialMediaID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.SocialMediaID;
				}
				set
				{
					mInstance.SocialMediaID = value;
				}
			}


			/// <summary>
			/// Title.
			/// </summary>
			public string Title
			{
				get
				{
					return mInstance.Title;
				}
				set
				{
					mInstance.Title = value;
				}
			}


			/// <summary>
			/// Target.
			/// </summary>
			public string Target
			{
				get
				{
					return mInstance.Target;
				}
				set
				{
					mInstance.Target = value;
				}
			}


			/// <summary>
			/// Redirect URL.
			/// </summary>
			public string RedirectUrl
			{
				get
				{
					return mInstance.RedirectUrl;
				}
				set
				{
					mInstance.RedirectUrl = value;
				}
			}


			/// <summary>
			/// Icon Class.
			/// </summary>
			public string IconClass
			{
				get
				{
					return mInstance.IconClass;
				}
				set
				{
					mInstance.IconClass = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="SocialMedia" /> class.
		/// </summary>
		public SocialMedia() : base(CLASS_NAME)
		{
			mFields = new SocialMediaFields(this);
		}

		#endregion
	}
}