//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.GDI;

[assembly: RegisterDocumentType(Subproduct.CLASS_NAME, typeof(Subproduct))]

namespace CMS.DocumentEngine.Types.GDI
{
	/// <summary>
	/// Represents a content item of type Subproduct.
	/// </summary>
	public partial class Subproduct : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "GDI.Subproduct";


		/// <summary>
		/// The instance of the class that provides extended API for working with Subproduct fields.
		/// </summary>
		private readonly SubproductFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// SubproductID.
		/// </summary>
		[DatabaseIDField]
		public int SubproductID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("SubproductID"), 0);
			}
			set
			{
				SetValue("SubproductID", value);
			}
		}


		/// <summary>
		/// Title.
		/// </summary>
		[DatabaseField]
		public string Title
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Title"), @"");
			}
			set
			{
				SetValue("Title", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with Subproduct fields.
		/// </summary>
		[RegisterProperty]
		public SubproductFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with Subproduct fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class SubproductFields : AbstractHierarchicalObject<SubproductFields>
		{
			/// <summary>
			/// The content item of type Subproduct that is a target of the extended API.
			/// </summary>
			private readonly Subproduct mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="SubproductFields" /> class with the specified content item of type Subproduct.
			/// </summary>
			/// <param name="instance">The content item of type Subproduct that is a target of the extended API.</param>
			public SubproductFields(Subproduct instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// SubproductID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.SubproductID;
				}
				set
				{
					mInstance.SubproductID = value;
				}
			}


			/// <summary>
			/// Title.
			/// </summary>
			public string Title
			{
				get
				{
					return mInstance.Title;
				}
				set
				{
					mInstance.Title = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="Subproduct" /> class.
		/// </summary>
		public Subproduct() : base(CLASS_NAME)
		{
			mFields = new SubproductFields(this);
		}

		#endregion
	}
}