//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.CustomTables;
using CMS.CustomTables.Types.GDI;

[assembly: RegisterCustomTable(CountriesItem.CLASS_NAME, typeof(CountriesItem))]

namespace CMS.CustomTables.Types.GDI
{
	/// <summary>
	/// Represents a content item of type CountriesItem.
	/// </summary>
	public partial class CountriesItem : CustomTableItem
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "GDI.Countries";


		/// <summary>
		/// The instance of the class that provides extended API for working with CountriesItem fields.
		/// </summary>
		private readonly CountriesItemFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// Country.
		/// </summary>
		[DatabaseField]
		public string Country
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Country"), @"");
			}
			set
			{
				SetValue("Country", value);
			}
		}


		/// <summary>
		/// Abbreviation.
		/// </summary>
		[DatabaseField]
		public string Abbreviation
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Abbreviation"), @"");
			}
			set
			{
				SetValue("Abbreviation", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with CountriesItem fields.
		/// </summary>
		[RegisterProperty]
		public CountriesItemFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with CountriesItem fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class CountriesItemFields : AbstractHierarchicalObject<CountriesItemFields>
		{
			/// <summary>
			/// The content item of type CountriesItem that is a target of the extended API.
			/// </summary>
			private readonly CountriesItem mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="CountriesItemFields" /> class with the specified content item of type CountriesItem.
			/// </summary>
			/// <param name="instance">The content item of type CountriesItem that is a target of the extended API.</param>
			public CountriesItemFields(CountriesItem instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// Country.
			/// </summary>
			public string Country
			{
				get
				{
					return mInstance.Country;
				}
				set
				{
					mInstance.Country = value;
				}
			}


			/// <summary>
			/// Abbreviation.
			/// </summary>
			public string Abbreviation
			{
				get
				{
					return mInstance.Abbreviation;
				}
				set
				{
					mInstance.Abbreviation = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="CountriesItem" /> class.
		/// </summary>
		public CountriesItem() : base(CLASS_NAME)
		{
			mFields = new CountriesItemFields(this);
		}

		#endregion
	}
}